# mysql pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci4-pvc-db
  labels:
    app: ci4app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  

#mysql service
---
apiVersion: v1
kind: Service
metadata:
  name: ci4-db # host
  labels:
    app: ci4app
spec:
  ports:
  - name: ci4-db
    port: 3306
    targetPort: 3306
  selector:
    app: ci4app
    

#mysql deployment
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ci4-db-deploy
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: ci4app      
  strategy:
    type: Recreate
  template: 
    metadata: 
      labels: 
        app: ci4app        
    spec:
      containers:
       - image: mariadb:latest
         name: ci4-mysql
         env:
         - name: MYSQL_DATABASE_HOST
           value: "ci4-db"
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
            secretKeyRef:
              name: ci4-secret
              key: password  
         - name: MYSQL_DATABASE
           value: "ci4"       
         - name: MYSQL_USER
           valueFrom:
            secretKeyRef:
              name: ci4-secret
              key: user 
         resources:
            limits:
              cpu: 800m # the CPU limit is define in milicore (m)
              memory: 800Mi # the Memory is define in Mebibytes (Mi)
            requests:
              cpu: 500m
         ports:
         - containerPort: 3306
           name: ci4-mysql 
           protocol: TCP
         volumeMounts:
         - name: ci4-volume
           mountPath: /var/lib/mysql
      volumes:
      - name: ci4-volume
        persistentVolumeClaim:
          claimName: ci4-pvc-db
