apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci4app
spec:
  selector:
    matchLabels:
      run: ci4app
  template:
    metadata:
      labels:
        run: ci4app
    spec:
      containers:
      - name: ci4app
        image: 127.0.0.1:5100/ci4-kubernetes:1.2
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ci4app
spec:
  selector:
    run: ci4app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30070
    protocol: TCP
  type: NodePort 
  

